name: deploy-on-success
description: Create a deployment on success
inputs:
  token:
    description: GitHub API OAuth token
    required: true
runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
  post-if: success()
