name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Prepare Nix auth
      run: |
        sudo mkdir -p /etc/systemd/system/nix-daemon.service.d
        sudo tee -a /etc/systemd/system/nix-daemon.service.d/auth.conf > /dev/null << EOF
        [Service]
        Environment="GITHUB_TOKEN=$GITHUB_TOKEN"
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/g5wb6882xaw11m5ygq2k9l6mqi6jalqa/install
        install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Cachix
      uses: cachix/cachix-action@v10
      with:
        name: portier
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build
      run: |
        nix build -vL
