name: build
concurrency: build-${{ github.ref }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_run:
    types: [completed]
    workflows:
    - update flakes
    - update testing broker
    - update testing demo

jobs:
  build:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Deploy on success
      uses: ./.github/actions/deploy-on-success
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare Nix auth
      run: |
        sudo mkdir -p /etc/systemd/system/nix-daemon.service.d
        sudo tee -a /etc/systemd/system/nix-daemon.service.d/auth.conf > /dev/null << EOF
        [Service]
        Environment="GITHUB_TOKEN=$GITHUB_TOKEN"
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/6zr15z4wr2fv99k9vdvw64svpz7y4hv6/install
        install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Cachix
      uses: cachix/cachix-action@v10
      with:
        name: portier
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build
      run: |
        nix build -vL
        echo "DEPLOY_STORE_PATH=$(readlink result)" >> $GITHUB_ENV
