name: update testing demo
concurrency: update_testing_demo

on: workflow_dispatch

jobs:

  check:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Find download
      id: find_download
      uses: ./.github/actions/find-green-download
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: portier
        repo: demo-rp

    - name: Check URL
      id: check_url
      run: |
        current="$(jq '.demo.url' ./server-config/portier-testing/sources.json)"
        echo "Current URL: $current"
        if [[ "$current" == '${{ steps.find_download.outputs.tarball_url }}' ]]; then
          echo "URL is unchanged"
        else
          echo "URL has changed"
          echo "::set-output name=did_change::1"
        fi

    - name: Download
      if: ${{ steps.check_url.outputs.did_change }}
      run: curl -L -o artifact.zip '${{ steps.find_download.outputs.tarball_url }}'

    - name: Modify config
      if: ${{ steps.check_url.outputs.did_change }}
      run: |
        jq \
          --arg url '${{ steps.find_download.outputs.tarball_url }}' \
          --arg hash "$(sha256sum -b source.tgz | awk '{ print $1 }')" \
          '.demo = { url: $url, sha256: $hash }' \
          ./server-config/portier-testing/sources.json \
          > scratch.json
        mv scratch.json ./server-config/portier-testing/sources.json

        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git commit -m 'Update portier-demo testing' \
          ./server-config/portier-testing/sources.json

    - name: Push
      if: ${{ steps.check_url.outputs.did_change }}
      run: |
        git pull --rebase
        git push origin main

    - name: Start build
      if: ${{ steps.check_url.outputs.did_change }}
      run: gh workflow run build.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
