name: update testing broker
concurrency: update_testing_broker

on: workflow_dispatch

jobs:

  check:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Find download
      id: find_download
      uses: ./.github/actions/find-green-download
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: portier
        repo: portier-broker
        artifact: 'Linux binary (debug)'

    - name: Check URL
      id: check_url
      run: |
        current="$(jq '.broker.url' ./server-config/portier-testing/sources.json)"
        echo "Current URL: $current"
        if [[ "$current" == '${{ steps.find_download.outputs.artifact_url }}' ]]; then
          echo "URL has changed"
          echo "::set-output name=did_change::1"
        else
          echo "URL is unchanged"
        fi

    outputs:
      artifact_url: ${{ steps.find_download.outputs.artifact_url }}
      did_change: ${{ steps.check_url.outputs.did_change }}

  update:
    needs: check
    if: ${{ needs.check.outputs.did_change }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Download
      run: |
        wget --http-user token --http-password '${{ secrets.GITHUB_TOKEN }}' \
          -o artifact.zip '${{ needs.check.outputs.artifact_url }}'

    - name: Modify config
      run: |
        jq \
          --arg url '${{ needs.check.outputs.artifact_url }}' \
          --arg hash "$(sha256sum -b artifact.zip | awk '{ print $1 }')" \
          '.broker.url = url | .broker.sha256 = hash' \
          ./server-config/portier-testing/sources.json \
          > scratch.json
        mv scratch.json ./server-config/portier-testing/sources.json

    # NOTE: Matches build.yml
    - name: Prepare Nix auth
      run: |
        sudo mkdir -p /etc/systemd/system/nix-daemon.service.d
        sudo tee -a /etc/systemd/system/nix-daemon.service.d/auth.conf > /dev/null << EOF
        [Service]
        Environment="GITHUB_TOKEN=$GITHUB_TOKEN"
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # NOTE: Matches build.yml
    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/g5wb6882xaw11m5ygq2k9l6mqi6jalqa/install
        install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve
        extra_nix_config: |
          experimental-features = nix-command flakes

    # NOTE: Matches build.yml
    - name: Cachix
      uses: cachix/cachix-action@v10
      with:
        name: portier
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Prepare download
      run: nix-store --add-fixed sha256 artifact.zip

    # NOTE: Matches build.yml
    - name: Build
      run: |
        nix build -vL

    - uses: EndBug/add-and-commit@v7.2.1
      with:
        add: './server-config/portier-testing/sources.json'
        default_author: github_actions
        message: 'Update portier-broker testing'
        pull_strategy: '--rebase'
